name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send commit info to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          COMMITS=$(git log -n 5 --pretty=format:"%h %s")
          
          COUNT=1
          FORMATTED_COMMITS=""
          while IFS= read -r line; do
            FORMATTED_COMMITS="${FORMATTED_COMMITS}${COUNT}. \`${line}\`\n"
            COUNT=$((COUNT + 1))
          done <<< "$COMMITS"

          MESSAGE="**New push to \`main\` branch. Latest commits:**\n\n${FORMATTED_COMMITS}"

          curl -X POST -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\"}" \
               $DISCORD_WEBHOOK_URL
