name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
            BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
            SHORT_SHA=$(git rev-parse --short HEAD)
            AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
            COMMIT_MSG=$(git log -1 --pretty=format:'%s')

            # Make sure history is deep enough to compare
            git fetch --depth=2
            FILE_COUNT=$(git diff --name-only HEAD^ HEAD | wc -l)
            COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"

            MESSAGE=$(jq -n \
              --arg msg "$COMMIT_MSG" \
              --arg author "$AUTHOR_NAME" \
              --arg branch "$BRANCH_NAME" \
              --arg sha "$SHORT_SHA" \
              --arg files "$FILE_COUNT" \
              --arg url "$COMMIT_URL" \
              '{content: "📢 **New Commit to `\($branch)`**\n\n👤 **Author:** \($author)\n🔢 **Commit:** `\($sha)`\n📝 **Message:** \($msg)\n📁 **Files Changed:** \($files)\n🔗 [View Commit](\($url))"}')

            curl -X POST -H "Content-Type: application/json" \
                 -d "$MESSAGE" \
                 $DISCORD_WEBHOOK_URL

