name: Notify Discord on Push

on:
  push:
    branches:
      - main  # Change this to whatever branch you want notifications for (e.g., 'develop')

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send commit info to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}  # Use the secret here
        run: |
            COMMITS=$(git log -n 5 --pretty=format:"%h %s")
            MESSAGE="Commits pushed to the main branch:\n$COMMITS"

            # Use jq to properly escape the message
            PAYLOAD=$(jq -n --arg content "$MESSAGE" '{content: $content}')

            curl -X POST -H "Content-Type: application/json" \
                 -d "$PAYLOAD" \
                 $DISCORD_WEBHOOK_URL
