name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
            BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
            SHORT_SHA=$(git rev-parse --short HEAD)
            AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
            COMMIT_MSG=$(git log -1 --pretty=format:'%s')

            # Get changed files and escape newlines/quotes
            FILES_CHANGED=$(git diff-tree --no-commit-id --name-only -r HEAD | sed 's/^/• /' | jq -Rs .)

            # Escape the commit message and author too, just in case
            ESCAPED_MSG=$(echo "$COMMIT_MSG" | jq -Rs .)
            ESCAPED_AUTHOR=$(echo "$AUTHOR_NAME" | jq -Rs .)

            MESSAGE=$(jq -n \
            --arg branch "$BRANCH_NAME" \
            --arg author "$AUTHOR_NAME" \
            --arg sha "$SHORT_SHA" \
            --arg msg "$COMMIT_MSG" \
            --arg files "$(git diff-tree --no-commit-id --name-only -r HEAD | sed 's/^/• /' | jq -Rs .)" \
              '{content: "🚀  **New Commit Pushed**\n\n**Branch:** `\($branch)`\n**Author:** \($author)\n**Commit:** `\($sha)`\n**Message:** \($msg)\n\n**Files Changed:**\n\($files)"}')

            curl -X POST -H "Content-Type: application/json" \
                 -d "$MESSAGE" \
                 $DISCORD_WEBHOOK_URL

