name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          ACTOR="${{ github.actor }}"
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          COMMIT_SHA="${{ github.event.head_commit.id }}"
          SHORT_SHA=$(echo $COMMIT_SHA | cut -c1-7)

          MESSAGE="**New commit to \`main\`**\n\n**Author:** $ACTOR\n**Commit:** \`$SHORT_SHA\`\n**Message:** $COMMIT_MSG"

          curl -X POST -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\"}" \
               $DISCORD_WEBHOOK_URL
