name: Notify Discord on Push

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
          COMMIT_HASH=$(git log -1 --pretty=format:"%h")
          AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
          COMMIT_MSG=$(git log -1 --pretty=format:"%s")

          MESSAGE="📦 New Push to Branch \`${BRANCH_NAME}\`\n**Author:** ${AUTHOR_NAME}\n**Commit:** \`${COMMIT_HASH}\` — _${COMMIT_MSG}_"

          curl -X POST -H "Content-Type: application/json" \
               -d "{\"content\": \"$MESSAGE\"}" \
               $DISCORD_WEBHOOK_URL
